import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <main className='w-[375px] h-[676px] bg-red-500 flex items-center justify-center'>
          <div className='w-[90%] border h-[90%] flex items-center justify-center'>{children}</div>
        </main>
      </body>
    </html>
  );
}
